INSERT INTO users (name, age) VALUES ('Avi', 28);
INSERT INTO users (name, age) VALUES ('Avei', 28);
INSERT INTO users (name, age) VALUES ('Avid', 28);
INSERT INTO users (name, age) VALUES ('Avia', 28);
INSERT INTO users (name, age) VALUES ('Avwi', 28);
INSERT INTO users (name, age) VALUES ('Avwqi', 28);
INSERT INTO users (name, age) VALUES ('Avrfi', 28);
INSERT INTO users (name, age) VALUES ('Avidddd', 28);
INSERT INTO users (name, age) VALUES ('Avasfi', 28);
INSERT INTO users (name, age) VALUES ('dsdadAvi', 28);
INSERT INTO users (name, age) VALUES ('Avssi', 28);
INSERT INTO users (name, age) VALUES ('Avxvi', 28);
INSERT INTO users (name, age) VALUES ('Avivg', 28);
INSERT INTO users (name, age) VALUES ('Avgggi', 28);
INSERT INTO users (name, age) VALUES ('Avhhhi', 28);
INSERT INTO users (name, age) VALUES ('Avjhgi', 28);
INSERT INTO users (name, age) VALUES ('Ahjyujuvi', 28);
INSERT INTO users (name, age) VALUES ('Avloli', 28);
INSERT INTO users (name, age) VALUES ('Avlmaoi', 28);
INSERT INTO users (name, age) VALUES ('Avhrhi', 28);

INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ('yes', 'category', 1000, '2/3/2018', '3/3/2018');
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ('yes', 'category', 1000, '2/3/2018', '3/3/2018');
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ('yes', 'category', 1000, '2/3/2018', '3/3/2018');
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ('yes', 'category', 1000, '2/3/2018', '3/3/2018');
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ('yes', 'category', 1000, '2/3/2018', '3/3/2018');
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ('yes', 'category', 1000, '2/3/2018', '3/3/2018');
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ('yes', 'category', 1000, '2/3/2018', '3/3/2018');
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ('yes', 'category', 1000, '2/3/2018', '3/3/2018');
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ('yes', 'category', 1000, '2/3/2018', '3/3/2018');
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ('yes', 'category', 1000, '2/3/2018', '3/3/2018');

INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
